openapi: '3.0.2'
info:
  title: Test OpenAPI
  version: '1.0'
servers:
  - url: https://api.server.test/v1
components:
  schemas:
    NumericTypes:
      type: object
      properties:
        smallNumbers:
          type: integer
          minimum: 1
          maximum: 20
        largeNumbers:
          type: number
          minimum: 1000
        tens:
          type: number
          multipleOf: 10
          minimum: 0
          maximum: 99
        listOfNumbers:
          type: array
          items:
            type: number
            minimum: -100
            maximum: 100
          minItems: 1
          maxItems: 10
    StringTypes:
      type: object
      properties:
        shortString:
          type: string
          minLength: 5
          maxLength: 20
paths:
  /test:
    get:
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NumericTypes"
  /test-allof:
    get:
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/NumericTypes"
                  - $ref: "#/components/schemas/StringTypes"
                  - type: object
                    required:
                      - smallNumbers
                      - shortString
  /test-multiple-responses/{id}:
    get:
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
        '404':
          description: 'Not found'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Not found
        default:
          description: 'Generic error'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Generic error
